# Generated by Django 3.2.3 on 2021-05-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=200, unique=True)),
                ('translation', models.CharField(default='', max_length=200)),
                ('state', models.IntegerField(default=0)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
