# Generated by Django 3.2.3 on 2021-05-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryInverted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=200, unique=True)),
                ('translation', models.CharField(default='', max_length=200)),
                ('state', models.IntegerField(default=0)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
