# Generated by Django 3.2.3 on 2021-05-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0002_dictionaryinverted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='translation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='word',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='dictionaryinverted',
            name='translation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dictionaryinverted',
            name='word',
            field=models.TextField(default='', unique=True),
        ),
    ]
