# Generated by Django 3.2.3 on 2021-05-26 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0005_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_created',
            new_name='dateCreated',
        ),
    ]
