# Generated by Django 3.2.3 on 2021-05-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0006_rename_date_created_question_datecreated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='AnswerOptions',
        ),
    ]
