# Generated by Django 3.2.3 on 2021-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0007_rename_answer_answeroptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroptions',
            name='wordId',
            field=models.IntegerField(default=0),
        ),
    ]
