# Generated by Django 3.2.3 on 2021-05-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0008_answeroptions_wordid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='lingvoapp.question'),
        ),
    ]
