# Generated by Django 3.2.3 on 2021-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0009_alter_answeroptions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='youtube',
            field=models.TextField(default=None),
        ),
    ]
