# Generated by Django 3.2.3 on 2021-05-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0010_material_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='youtube',
            field=models.TextField(default=''),
        ),
    ]
