# Generated by Django 3.2.3 on 2021-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0011_alter_material_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='youtube',
            field=models.TextField(default='https://www.youtube.com/embed/y3T56egqXLw'),
        ),
    ]
