# Generated by Django 3.2.3 on 2021-05-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lingvoapp', '0013_rename_youtube_material_youtubeurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='youtubeUrl',
        ),
    ]
